In [1]:
import numpy as np
from basis_states import *
from hamiltonian import *
import symmer 

In [86]:
N = 4

In [87]:
mesons, baryons = get_basis(N)

In [88]:
Qx = Qx_tot(N)
Qy = Qy_tot(N)

In [99]:
color_singlets(N, baryons)

set()


[ 1.000+0.000j |00000011>,
  1.000+0.000j |00001100>,
  1.000+0.000j |00110000>,
  1.000+0.000j |11000000>,
  0.707+0.000j |00000110> +
 -0.707+0.000j |00001001>,
  0.707+0.000j |00010010> +
 -0.707+0.000j |00100001>,
  0.707+0.000j |00011000> +
 -0.707+0.000j |00100100>,
  0.707+0.000j |01000010> +
 -0.707+0.000j |10000001>,
  0.707+0.000j |01001000> +
 -0.707+0.000j |10000100>,
  0.707+0.000j |01100000> +
 -0.707+0.000j |10010000>]

In [89]:
from symmer.projection import QubitTapering

QT_X = QubitTapering(Qx, target_sqp='Z')
# print(QT.symmetry_generators)
print(QT_X.symmetry_generators.rotate_onto_single_qubit_paulis())

stabilizer_rotations = QT_X.symmetry_generators.stabilizer_rotations

Qx_inZ_basis = Qx.perform_rotations(stabilizer_rotations)
Qx_inZ_basis

from symmer.projection import QubitTapering

QT_Y = QubitTapering(Qy, target_sqp='Z')
# print(QT.symmetry_generators)
print(QT_Y.symmetry_generators.rotate_onto_single_qubit_paulis())

stabilizer_rotations_Y = QT_Y.symmetry_generators.stabilizer_rotations

Qy_inZ_basis = Qy.perform_rotations(stabilizer_rotations_Y)
Qy_inZ_basis

-1 IIIIIIIZ 
1 IIIIIIZI 
-1 IIIIIZII 
1 IIIIZIII 
-1 IIIZIIII 
1 IIZIIIII 
-1 IZIIIIII 
1 ZIIIIIII
-1 IIIIIIIZ 
-1 IIIIIIZI 
-1 IIIIIZII 
-1 IIIIZIII 
-1 IIIZIIII 
-1 IIZIIIII 
-1 IZIIIIII 
-1 ZIIIIIII


 0.250-0.000j IIIIIIIZ +
 0.250-0.000j IIIIIIZZ +
 0.250-0.000j IIIIIZII +
 0.250-0.000j IIIIZZII +
 0.250-0.000j IIIZIIII +
 0.250-0.000j IIZZIIII +
 0.250-0.000j IZIIIIII +
 0.250-0.000j ZZIIIIII

In [90]:
from symmer.evolution.exponentiation import exponentiate_single_Pop

Ry = sym.PauliwordOp.from_list(['I'*Qy.n_terms])
for index, (P_k, angle) in enumerate(stabilizer_rotations_Y[::-1]):
    angle = 1j*np.pi/4
    Ry*=exponentiate_single_Pop(P_k.multiply_by_constant(angle))

print(Ry * Qy * Ry.dagger, "\n")

Rx = sym.PauliwordOp.from_list(['I'*Qx.n_terms])
for index, (P_k, angle) in enumerate(stabilizer_rotations[::-1]):
    angle = 1j*np.pi/4
    Rx*=exponentiate_single_Pop(P_k.multiply_by_constant(angle))

print(Rx * Qx * Rx.dagger)

 0.250+0.000j IIIIIIIZ +
 0.250+0.000j IIIIIIZZ +
 0.250+0.000j IIIIIZII +
 0.250+0.000j IIIIZZII +
 0.250+0.000j IIIZIIII +
 0.250+0.000j IIZZIIII +
 0.250+0.000j IZIIIIII +
 0.250+0.000j ZZIIIIII 

 0.250+0.000j IIIIIIZI +
 0.250+0.000j IIIIIIZZ +
 0.250+0.000j IIIIZIII +
 0.250+0.000j IIIIZZII +
 0.250+0.000j IIZIIIII +
 0.250+0.000j IIZZIIII +
 0.250+0.000j ZIIIIIII +
 0.250+0.000j ZZIIIIII


In [91]:
import itertools
allowed_Y_1 = [(1,0), (1,1)]
allowed_Y_2 = [(0, 0), (0, 1)]
product1 = list(itertools.product(allowed_Y_1, repeat=N))
product2 = list(itertools.product(allowed_Y_2, repeat = N))

bad_product2 = []
for i in product2:
    for j in np.arange(0, N - 1, 2):
        if i[j] == i[j + 1]:
            bad_product2.append(i)
product2 = list(set(product2) ^ set(bad_product2))

arr1 = np.array(product1)
arr2 = np.array(product2)
arr = np.concatenate((arr1, arr2))
arr_updated = arr.reshape(arr.shape[0],-1)

arr_updated

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0]])

In [92]:
solutions = {}
for i in range(arr.shape[0]):
    #state =  sym.QuantumState(arr[i,:].reshape([1,-1]), [1]) 
    state =  sym.QuantumState(arr_updated[i,:].reshape([1,-1]), [1]) 
    
    # solutions[i] = Ry.dagger * state
    rotated_state = Ry.dagger * state
    mask = np.abs(rotated_state.state_op.coeff_vec.real)>1e-12
    real_state_matrix = rotated_state.state_matrix[mask]
    coeff = rotated_state.state_op.coeff_vec[mask]
    solutions[i] = sym.QuantumState(real_state_matrix, coeff).normalize
    
    #solutions[i] = state

solutions

{0:  0.354+0.000j |00000000> +
 -0.354+0.000j |00001111> +
 -0.354+0.000j |00110011> +
 -0.354+0.000j |00111100> +
 -0.354+0.000j |11000011> +
 -0.354+0.000j |11001100> +
 -0.354+0.000j |11110000> +
  0.354+0.000j |11111111>,
 1: -0.354+0.000j |00000011> +
  0.354+0.000j |00001100> +
  0.354+0.000j |00110000> +
  0.354+0.000j |00111111> +
  0.354+0.000j |11000000> +
  0.354+0.000j |11001111> +
  0.354+0.000j |11110011> +
 -0.354+0.000j |11111100>,
 2:  0.354+0.000j |00000011> +
 -0.354+0.000j |00001100> +
  0.354+0.000j |00110000> +
  0.354+0.000j |00111111> +
  0.354+0.000j |11000000> +
  0.354+0.000j |11001111> +
 -0.354+0.000j |11110011> +
  0.354+0.000j |11111100>,
 3: -0.354+0.000j |00000000> +
  0.354+0.000j |00001111> +
 -0.354+0.000j |00110011> +
 -0.354+0.000j |00111100> +
 -0.354+0.000j |11000011> +
 -0.354+0.000j |11001100> +
  0.354+0.000j |11110000> +
 -0.354+0.000j |11111111>,
 4:  0.354+0.000j |00000011> +
  0.354+0.000j |00001100> +
 -0.354+0.000j |00110000> +
  0.354+0

In [93]:
non_single_solns = []
for state in solutions.values():
    kill_state = 0
    for indiv_state in state:
        kill_state += (Qy*indiv_state).n_terms
    if kill_state != 0:
        non_single_solns.append(state)
non_single_solns
    

[-0.354+0.000j |01010101> +
 -0.354+0.000j |01011010> +
 -0.354+0.000j |01100110> +
  0.354+0.000j |01101001> +
  0.354+0.000j |10010110> +
 -0.354+0.000j |10011001> +
 -0.354+0.000j |10100101> +
 -0.354+0.000j |10101010>,
 -0.354+0.000j |01010101> +
 -0.354+0.000j |01011010> +
 -0.354+0.000j |01100110> +
  0.354+0.000j |01101001> +
  0.354+0.000j |10010110> +
 -0.354+0.000j |10011001> +
 -0.354+0.000j |10100101> +
 -0.354+0.000j |10101010>,
 -0.354+0.000j |01010101> +
 -0.354+0.000j |01011010> +
  0.354+0.000j |01100110> +
 -0.354+0.000j |01101001> +
 -0.354+0.000j |10010110> +
  0.354+0.000j |10011001> +
 -0.354+0.000j |10100101> +
 -0.354+0.000j |10101010>,
 -0.354+0.000j |01010101> +
 -0.354+0.000j |01011010> +
  0.354+0.000j |01100110> +
 -0.354+0.000j |01101001> +
 -0.354+0.000j |10010110> +
  0.354+0.000j |10011001> +
 -0.354+0.000j |10100101> +
 -0.354+0.000j |10101010>]

In [94]:
for state in non_single_solns:
    print(state, ":", B(N) * state, "\n")

-0.354+0.000j |01010101> +
-0.354+0.000j |01011010> +
-0.354+0.000j |01100110> +
 0.354+0.000j |01101001> +
 0.354+0.000j |10010110> +
-0.354+0.000j |10011001> +
-0.354+0.000j |10100101> +
-0.354+0.000j |10101010> :  

-0.354+0.000j |01010101> +
-0.354+0.000j |01011010> +
-0.354+0.000j |01100110> +
 0.354+0.000j |01101001> +
 0.354+0.000j |10010110> +
-0.354+0.000j |10011001> +
-0.354+0.000j |10100101> +
-0.354+0.000j |10101010> :  

-0.354+0.000j |01010101> +
-0.354+0.000j |01011010> +
 0.354+0.000j |01100110> +
-0.354+0.000j |01101001> +
-0.354+0.000j |10010110> +
 0.354+0.000j |10011001> +
-0.354+0.000j |10100101> +
-0.354+0.000j |10101010> :  

-0.354+0.000j |01010101> +
-0.354+0.000j |01011010> +
 0.354+0.000j |01100110> +
-0.354+0.000j |01101001> +
-0.354+0.000j |10010110> +
 0.354+0.000j |10011001> +
-0.354+0.000j |10100101> +
-0.354+0.000j |10101010> :  



In [ ]:
def remove_states(qy_solutions, to_be_removed):
    return 

In [ ]:
def color_neutral_basis(states, sector):
    
    return

In [29]:
baryons, mesons

([ 1.000+0.000j |0000>],
 [ 1.000+0.000j |0011>,
   1.000+0.000j |0110>,
   1.000+0.000j |1001>,
   1.000+0.000j |1100>])

In [14]:
individual_solns = []
for state in solutions.values(): 
    # print(Qy * state)

    for indiv_state in state:
        if indiv_state.state_matrix.tolist() not in individual_solns:
          if (Qy * indiv_state).n_terms==0:
            individual_solns.append(tuple(*indiv_state.state_matrix.tolist()))


individual_solns

[(0, 0, 0, 0, 0, 0, 0, 0),
 (0, 0, 0, 0, 0, 0, 1, 1),
 (0, 0, 0, 0, 1, 1, 0, 0),
 (0, 0, 0, 0, 1, 1, 1, 1),
 (0, 0, 1, 1, 0, 0, 0, 0),
 (0, 0, 1, 1, 0, 0, 1, 1),
 (0, 0, 1, 1, 1, 1, 0, 0),
 (0, 0, 1, 1, 1, 1, 1, 1),
 (1, 1, 0, 0, 0, 0, 0, 0),
 (1, 1, 0, 0, 0, 0, 1, 1),
 (1, 1, 0, 0, 1, 1, 0, 0),
 (1, 1, 0, 0, 1, 1, 1, 1),
 (1, 1, 1, 1, 0, 0, 0, 0),
 (1, 1, 1, 1, 0, 0, 1, 1),
 (1, 1, 1, 1, 1, 1, 0, 0),
 (1, 1, 1, 1, 1, 1, 1, 1),
 (0, 0, 0, 0, 0, 0, 0, 0),
 (0, 0, 0, 0, 0, 0, 1, 1),
 (0, 0, 0, 0, 1, 1, 0, 0),
 (0, 0, 0, 0, 1, 1, 1, 1),
 (0, 0, 1, 1, 0, 0, 0, 0),
 (0, 0, 1, 1, 0, 0, 1, 1),
 (0, 0, 1, 1, 1, 1, 0, 0),
 (0, 0, 1, 1, 1, 1, 1, 1),
 (1, 1, 0, 0, 0, 0, 0, 0),
 (1, 1, 0, 0, 0, 0, 1, 1),
 (1, 1, 0, 0, 1, 1, 0, 0),
 (1, 1, 0, 0, 1, 1, 1, 1),
 (1, 1, 1, 1, 0, 0, 0, 0),
 (1, 1, 1, 1, 0, 0, 1, 1),
 (1, 1, 1, 1, 1, 1, 0, 0),
 (1, 1, 1, 1, 1, 1, 1, 1),
 (0, 0, 0, 0, 0, 0, 0, 0),
 (0, 0, 0, 0, 0, 0, 1, 1),
 (0, 0, 0, 0, 1, 1, 0, 0),
 (0, 0, 0, 0, 1, 1, 1, 1),
 (0, 0, 1, 1, 0, 0, 0, 0),
 

In [250]:
solutions[1].state_matrix.tolist()

[[0, 0, 1, 1], [1, 1, 0, 0]]

In [256]:
set(tuple(bits) for bits in solutions[1].state_matrix)

[{0, 1}, {0, 1}]

In [182]:
for i in solutions.keys():
    print(Qy * solutions[i])
    print(Qx * solutions[i])

In [176]:
# rotated_state.state_matrix


array([[0, 1, 1, 0],
       [1, 0, 0, 1]])

In [162]:
for state in solutions: 
    print(solutions[state], "\n")

 0.500+0.000j |0000> +
 0.000-0.500j |0011> +
 0.000-0.500j |1100> +
-0.500+0.000j |1111> 

 0.000+0.500j |0000> +
-0.500+0.000j |0011> +
 0.500+0.000j |1100> +
 0.000+0.500j |1111> 

 0.000+0.500j |0000> +
 0.500+0.000j |0011> +
-0.500+0.000j |1100> +
 0.000+0.500j |1111> 

-0.500+0.000j |0000> +
 0.000-0.500j |0011> +
 0.000-0.500j |1100> +
 0.500+0.000j |1111> 

 0.000-0.500j |0101> +
-0.500+0.000j |0110> +
 0.500+0.000j |1001> +
 0.000-0.500j |1010> 

 0.000-0.500j |0101> +
 0.500+0.000j |0110> +
-0.500+0.000j |1001> +
 0.000-0.500j |1010> 



In [157]:
mesons, baryons

([ 1.000+0.000j |0011>,
   1.000+0.000j |0110>,
   1.000+0.000j |1001>,
   1.000+0.000j |1100>],
 [ 1.000+0.000j |0000>])

In [278]:
n_qubits=4

bitstrings = (
                (
                        np.arange(2 ** n_qubits).reshape([-1, 1]) &
                        (1 << np.arange(n_qubits))[::-1]
                ) > 0).astype(int)

binary_int_array = 1 << np.arange(n_qubits - 1, -1, -1)

In [279]:
out_base_10 = bitstrings @ binary_int_array
out_base_10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [280]:
allowed = [1,4,6]

missing = np.setdiff1d(out_base_10, allowed)

missing_bitstrings = (
                (
                        missing.reshape([-1, 1]) &
                        (1 << np.arange(n_qubits))[::-1]
                ) > 0).astype(int)
missing_bitstrings

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 1],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

 0.381-0.065j |00> +
 0.785-0.364j |01> +
-0.200+0.229j |10> +
 0.059+0.068j |11>

In [16]:
def remove_basis_states_from_superposition(state, array_of_bitstrings):

    mask = np.zeros(state.state_matrix.shape[0], dtype=bool)
    for basis_state in array_of_bitstrings:
       mask = np.logical_or(mask, np.sum(state.state_matrix == basis_state, axis=1) == state.state_matrix.shape[1])

    return sym.QuantumState(state.state_matrix[~mask], state.state_op.coeff_vec[~mask])


In [17]:
state = sym.QuantumState.haar_random(2)
print(state)

remove_basis_states_from_superposition(state, np.array([[1,0],
                                                        [1,1]]))

-0.306-0.850j |00> +
-0.154-0.235j |01> +
-0.006-0.223j |10> +
 0.196+0.132j |11>


-0.306-0.850j |00> +
-0.154-0.235j |01>

In [18]:
def get_Qz_state(N):
    n_qubits = 2*N

    bitstrings = (
                    (
                            np.arange(2 ** n_qubits).reshape([-1, 1]) &
                            (1 << np.arange(n_qubits))[::-1]
                    ) > 0).astype(int)

    sign_array = np.array([(-1)**(i%2) for i in range(n_qubits)])
    Qz_mask = np.sum(bitstrings*sign_array, axis=1) == 0

    valid_bitstrings = bitstrings[Qz_mask, :]
    return valid_bitstrings

def get_valid_B(array_bitstrings, B_value):
    B_arr = (-1)**array_bitstrings * 1/4
    B_mask = np.sum(B_arr, axis=1) == B_value
    return array_bitstrings[B_mask, :]

In [28]:
B_val = 1
valid_Qz = get_Qz_state(N)
valid_Qz_and_B = get_valid_B(valid_Qz, B_val)
valid_Qz_and_B

array([[0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0]])

In [20]:
single_solutions=[]
for bitstring in valid_Qz_and_B:
    if (Qy * sym.QuantumState(bitstring.reshape([1,-1]))).n_terms==0:
        single_solutions.append(bitstring)

single_solutions = np.array(single_solutions)
single_solutions

array([[0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])

array([-1,  0])

In [33]:
# other illegal solutions
illegal_B_vals = np.setdiff1d([1,-1, 0], B_val)

remove_Bneg1 = get_valid_B(valid_Qz, illegal_B_vals[0])
remove_B1 = get_valid_B(valid_Qz, illegal_B_vals[1])


illegal = single_solutions
illegal = np.vstack((illegal, remove_Bneg1))
illegal = np.vstack((illegal, remove_B1))
illegal

array([[0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 0, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 1],
       [1, 1, 0, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1],
       [1, 1, 1, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 0, 0, 1],
       [0,

In [34]:
solutions = {}
for i in range(arr.shape[0]):
    #state =  sym.QuantumState(arr[i,:].reshape([1,-1]), [1]) 
    state =  sym.QuantumState(arr_updated[i,:].reshape([1,-1]), [1]) 
    
    # solutions[i] = Ry.dagger * state
    rotated_state = Ry.dagger * state
    rotated_state_no_ind_sol = remove_basis_states_from_superposition(rotated_state, 
                                                                      illegal)
    solutions[i] = rotated_state_no_ind_sol
solutions

{0:  0.250+0.000j |00000000> +
 -0.000-0.250j |00000011> +
 -0.000-0.250j |00001100> +
 -0.000-0.250j |00110000> +
 -0.000-0.250j |11000000> +
  0.250+0.000j |11111111>,
 1:  0.000+0.250j |00000000> +
 -0.250+0.000j |00000011> +
  0.250+0.000j |00001100> +
  0.250+0.000j |00110000> +
  0.250+0.000j |11000000> +
  0.000-0.250j |11111111>,
 2:  0.000+0.250j |00000000> +
  0.250+0.000j |00000011> +
 -0.250+0.000j |00001100> +
  0.250+0.000j |00110000> +
  0.250+0.000j |11000000> +
  0.000-0.250j |11111111>,
 3: -0.250+0.000j |00000000> +
  0.000-0.250j |00000011> +
  0.000-0.250j |00001100> +
  0.000+0.250j |00110000> +
  0.000+0.250j |11000000> +
 -0.250+0.000j |11111111>,
 4:  0.000+0.250j |00000000> +
  0.250+0.000j |00000011> +
  0.250+0.000j |00001100> +
 -0.250+0.000j |00110000> +
  0.250+0.000j |11000000> +
  0.000-0.250j |11111111>,
 5: -0.250+0.000j |00000000> +
  0.000-0.250j |00000011> +
  0.000+0.250j |00001100> +
  0.000-0.250j |00110000> +
  0.000+0.250j |11000000> +
 -0.250

In [35]:
solutions_real = {}
for key, state in solutions.items():
    if state.n_terms>0:
        mask = np.abs(state.state_op.coeff_vec.real)>1e-12
        real_state_matrix = state.state_matrix[mask]
        coeff = state.state_op.coeff_vec[mask]
        solutions_real[i] = sym.QuantumState(real_state_matrix, coeff).normalize

# dictionary hashing removes duplicated terms!
solutions_real

{19: -0.707+0.000j |01010101> +
 -0.707+0.000j |10101010>}

In [23]:
single_solutions

array([[0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])

In [42]:
psi = solutions_real[19].normalize
Qz_tot(N) * psi

-1.414+0.000j |01010101> +
 1.414+0.000j |10101010>

In [27]:
mesons

[ 1.000+0.000j |00001111>,
  1.000+0.000j |00011011>,
  1.000+0.000j |00011110>,
  1.000+0.000j |00100111>,
  1.000+0.000j |00101101>,
  1.000+0.000j |00110011>,
  1.000+0.000j |00110110>,
  1.000+0.000j |00111001>,
  1.000+0.000j |00111100>,
  1.000+0.000j |01001011>,
  1.000+0.000j |01001110>,
  1.000+0.000j |01011010>,
  1.000+0.000j |01100011>,
  1.000+0.000j |01100110>,
  1.000+0.000j |01101001>,
  1.000+0.000j |01101100>,
  1.000+0.000j |01110010>,
  1.000+0.000j |01111000>,
  1.000+0.000j |10000111>,
  1.000+0.000j |10001101>,
  1.000+0.000j |10010011>,
  1.000+0.000j |10010110>,
  1.000+0.000j |10011001>,
  1.000+0.000j |10011100>,
  1.000+0.000j |10100101>,
  1.000+0.000j |10110001>,
  1.000+0.000j |10110100>,
  1.000+0.000j |11000011>,
  1.000+0.000j |11000110>,
  1.000+0.000j |11001001>,
  1.000+0.000j |11001100>,
  1.000+0.000j |11010010>,
  1.000+0.000j |11011000>,
  1.000+0.000j |11100001>,
  1.000+0.000j |11100100>,
  1.000+0.000j |11110000>]