In [1]:
import numpy as np
from basis_states import *
from hamiltonian import *
import symmer as sym

In [2]:
N = 2
a, g, m = 1, 1, 1

In [3]:
H(N)

 2.188+0.000j IIII +
 0.500+0.000j IIIZ +
 0.500+0.000j IIZI +
-0.500+0.000j IZII +
-0.500+0.000j ZIII +
-0.188+0.000j ZZII +
-0.250+0.000j IXZX +
-0.250+0.000j IYZY +
-0.250+0.000j XZXI +
-0.250+0.000j YZYI

In [4]:
mesons, baryons = get_basis(N)

In [5]:
mesons, baryons

([ 1.000+0.000j |0011>,
   1.000+0.000j |0110>,
   1.000+0.000j |1001>,
   1.000+0.000j |1100>],
 [ 1.000+0.000j |0000>])

In [6]:
Qx = Qx_tot(N)
Qy = Qy_tot(N)

Qz = Qz_tot(N)

In [7]:
state1 = sym.QuantumState([[0, 1, 1, 0]])
state2 = sym.QuantumState([[1, 0, 0, 1]])
Qy * state1, Qy * state2

( 0.000-0.500j |0101> +
  0.000+0.500j |1010>,
  0.000-0.500j |0101> +
  0.000+0.500j |1010>)

Qx.dagger == Qx

Qx.commutes(Qy)

In [156]:
qxmat = Qx.to_sparse_matrix.toarray()

qymat = Qy.to_sparse_matrix.toarray()

In [157]:
vals, vecs = np.linalg.eigh(qxmat)

vals, vecs = np.linalg.eigh(qymat)

In [158]:
epsilon = 1e-10
vals[np.abs(vals) < epsilon] = 0
vals

array([-1. , -0.5, -0.5, -0.5, -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0.5,  0.5,  0.5,  0.5,  1. ])

In [159]:
np.where(vals == 0)[0]

array([ 5,  6,  7,  8,  9, 10])

In [160]:
tolerance = 0

solutions = []
for index in np.where(vals == 0)[0]:
    #vecs[:, index][np.abs(vecs[:, index]) < tolerance] = 0
    psi = sym.QuantumState.from_array(vecs[:, index].reshape([-1, 1]))
    if list((Qz_tot(N) * psi).to_dictionary.values())[0] == 0 and \
        list((B(N) * psi).to_dictionary.values())[0] == 0:
        print(psi, "\n")
        solutions.append(psi)

 0.707+0.000j |0110> +
-0.707+0.000j |1001> 

 1.000+0.000j |1100> 

 1.000+0.000j |0011> 



In [92]:
for sol in solutions:
    if sol.n_terms > 1:
        print(sol)
        print()

-0.707+0.000j |11010010> +
 0.707+0.000j |11100001>



In [56]:
state1 = sym.QuantumState.from_dictionary({'01100110': 1.0})
state2 = sym.QuantumState.from_dictionary({'10011001': 1.0})
state3 = sym.QuantumState.from_dictionary({'10010110': 1.0})
state4 = sym.QuantumState.from_dictionary({'01011010': 1.0})
state5 = sym.QuantumState.from_dictionary({'10100101': 1.0})
state6 = sym.QuantumState.from_dictionary({'01101001': 1.0})

for state in [state1, state2, state3, state4, state5, state6]:
    print([int(i, 2) for i in list((Qy * state).to_dictionary.keys())], 
          list((Qy * state).to_dictionary.values()),"\n")

[86, 101, 106, 166] [-0.5j, -0.5j, 0.5j, 0.5j] 

[89, 149, 154, 169] [-0.5j, -0.5j, 0.5j, 0.5j] 

[86, 149, 154, 166] [-0.5j, -0.5j, 0.5j, 0.5j] 

[86, 89, 106, 154] [-0.5j, -0.5j, 0.5j, 0.5j] 

[101, 149, 166, 169] [-0.5j, -0.5j, 0.5j, 0.5j] 

[89, 101, 106, 169] [-0.5j, -0.5j, 0.5j, 0.5j] 



In [855]:
state3 * 100

 100.000+0.000j |10010110>

In [161]:
len(mesons), sum([sol.n_terms for sol in solutions])

(4, 4)

In [755]:
index = 9
vecs[:, index][np.abs(vecs[:, index]) < epsilon] = 0
vecs[:, index]

array([ 0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.70710678+0.j,  0.        +0.j,
        0.        +0.j, -0.70710678+0.j,  0.        +0.j,  0.        +0.j,
        0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j])

In [756]:
psi = sym.QuantumState.from_array(vecs[:, index].reshape([-1, 1]))
psi

 0.707+0.000j |0110> +
-0.707+0.000j |1001>

In [757]:
Qy_tot(N) * psi 


In [758]:
Qx * psi

In [759]:
Qz = Qz_tot(N)
Qz

-0.250+0.000j IIIZ +
 0.250+0.000j IIZI +
-0.250+0.000j IZII +
 0.250+0.000j ZIII

In [760]:
mesons

[ 1.000+0.000j |0011>,
  1.000+0.000j |0110>,
  1.000+0.000j |1001>,
  1.000+0.000j |1100>]

In [761]:
B(N)

 0.250+0.000j IIIZ +
 0.250+0.000j IIZI +
 0.250+0.000j IZII +
 0.250+0.000j ZIII

In [762]:
(-1)**bitstrings * 1/4

array([[ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.25,  0.25, -0.25],
       [ 0.25,  0.25, -0.25,  0.25],
       [ 0.25,  0.25, -0.25, -0.25],
       [ 0.25, -0.25,  0.25,  0.25],
       [ 0.25, -0.25,  0.25, -0.25],
       [ 0.25, -0.25, -0.25,  0.25],
       [ 0.25, -0.25, -0.25, -0.25],
       [-0.25,  0.25,  0.25,  0.25],
       [-0.25,  0.25,  0.25, -0.25],
       [-0.25,  0.25, -0.25,  0.25],
       [-0.25,  0.25, -0.25, -0.25],
       [-0.25, -0.25,  0.25,  0.25],
       [-0.25, -0.25,  0.25, -0.25],
       [-0.25, -0.25, -0.25,  0.25],
       [-0.25, -0.25, -0.25, -0.25]])

In [137]:
## speedup choose Qz bitrings  by rules determined by combinations
# (number of spin up == spin down!)
n_qubits = 2*N

bitstrings = (
                (
                        np.arange(2 ** n_qubits).reshape([-1, 1]) &
                        (1 << np.arange(n_qubits))[::-1]
                ) > 0).astype(int)

sign_array = np.array([(-1)**(i%2) for i in range(n_qubits)])
Qz_mask = np.sum(bitstrings*sign_array, axis=1) == 0

## speedup by slicing bitstrings with Qz_mask!!!

B_arr = (-1)**bitstrings * 1/4
B_mask = np.logical_or(np.sum(B_arr, axis=1) == 0, np.sum(B_arr, axis=1) == 1)

print('valid B states:', np.sum(B_mask))
print('valid Qz states:', np.sum(Qz_mask))
QzandB_mask = np.logical_and(B_mask, Qz_mask)
print('valid Qz AND B states:', np.sum(QzandB_mask))
print('out of a possible:', 2**(2*N))
valid_bitstrings = bitstrings[QzandB_mask, :]
valid_bitstrings

valid B states: 98
valid Qz states: 70
valid Qz AND B states: 52
out of a possible: 256


array([[0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 1, 1],
       [0, 1, 1, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 0, 0],
       [1,

In [764]:
bitstrings[B_mask, :][0]

array([0, 0, 0, 0])

In [765]:
np.sum((bitstrings*1/4)[-2:,:], axis=1)

array([0.75, 1.  ])

In [766]:
for state in valid_bitstrings:
    psi = sym.QuantumState(state, [1])
    print(psi.dagger * B(N) * psi)

(1+0j)
0j
0j
0j
0j


In [767]:
Qy

-0.250+0.000j IIXY +
 0.250+0.000j IIYX +
-0.250+0.000j XYII +
 0.250+0.000j YXII

In [768]:
help(QT.symmetry_generators.rotate_onto_single_qubit_paulis)

Help on method rotate_onto_single_qubit_paulis in module symmer.operators.independent_op:

rotate_onto_single_qubit_paulis() -> 'IndependentOp' method of symmer.operators.independent_op.IndependentOp instance
    Returns the rotated single-qubit Pauli stabilizers.
    
    Returns: 
        Rotated single-qubit Pauli stabilizers.



In [11]:
from symmer.projection import QubitTapering

QT_X = QubitTapering(Qx, target_sqp='Z')
# print(QT.symmetry_generators)
print(QT_X.symmetry_generators.rotate_onto_single_qubit_paulis())

stabilizer_rotations = QT_X.symmetry_generators.stabilizer_rotations

Qx_inZ_basis = Qx.perform_rotations(stabilizer_rotations)
Qx_inZ_basis

-1 IIIZ 
1 IIZI 
-1 IZII 
1 ZIII


 0.250-0.000j IIZI +
 0.250-0.000j IIZZ +
 0.250-0.000j ZIII +
 0.250-0.000j ZZII

In [12]:
Qy


-0.250+0.000j IIXY +
 0.250+0.000j IIYX +
-0.250+0.000j XYII +
 0.250+0.000j YXII

In [8]:
from symmer.projection import QubitTapering

QT_Y = QubitTapering(Qy, target_sqp='Z')
# print(QT.symmetry_generators)
print(QT_Y.symmetry_generators.rotate_onto_single_qubit_paulis())

stabilizer_rotations_Y = QT_Y.symmetry_generators.stabilizer_rotations

Qy_inZ_basis = Qy.perform_rotations(stabilizer_rotations_Y)
Qy_inZ_basis

-1 IIIZ 
-1 IIZI 
-1 IZII 
-1 ZIII


 0.250-0.000j IIIZ +
 0.250-0.000j IIZZ +
 0.250-0.000j IZII +
 0.250-0.000j ZZII

In [9]:
from symmer.evolution.exponentiation import exponentiate_single_Pop

In [10]:
R = sym.PauliwordOp.from_list(['I'*Qy.n_terms])
for index, (P_k, angle) in enumerate(stabilizer_rotations_Y[::-1]):
    angle = 1j*np.pi/4
    R*=exponentiate_single_Pop(P_k.multiply_by_constant(angle))

R * Qy * R.dagger

 0.250+0.000j IIIZ +
 0.250+0.000j IIZZ +
 0.250+0.000j IZII +
 0.250+0.000j ZZII

In [11]:
eigvals, eigvecs = np.linalg.eigh(Qy_inZ_basis.to_sparse_matrix.toarray())
print('we expect:', sum(eigvals==0), 'solutions!')

we expect: 6 solutions!


In [12]:
indices = np.where(eigvals==0)[0]


all_solutions = [sym.QuantumState.from_array(eigvecs[:, ind].reshape([-1,1])) for ind in indices]
all_solutions

[ 1.000+0.000j |0001>,
  1.000+0.000j |1010>,
  1.000+0.000j |1011>,
  1.000+0.000j |0100>,
  1.000+0.000j |1110>,
  1.000+0.000j |1111>]

In [13]:
solutions_in_true_basis = {i: R.dagger * psi for i, psi in enumerate(all_solutions)}
solutions_in_true_basis

{0:  0.000-0.500j |0101> +
 -0.500+0.000j |0110> +
  0.500+0.000j |1001> +
  0.000-0.500j |1010>,
 1:  0.500+0.000j |0000> +
  0.000-0.500j |0011> +
  0.000-0.500j |1100> +
 -0.500+0.000j |1111>,
 2:  0.000+0.500j |0000> +
 -0.500+0.000j |0011> +
  0.500+0.000j |1100> +
  0.000+0.500j |1111>,
 3:  0.000-0.500j |0101> +
  0.500+0.000j |0110> +
 -0.500+0.000j |1001> +
  0.000-0.500j |1010>,
 4:  0.000+0.500j |0000> +
  0.500+0.000j |0011> +
 -0.500+0.000j |1100> +
  0.000+0.500j |1111>,
 5: -0.500+0.000j |0000> +
  0.000-0.500j |0011> +
  0.000-0.500j |1100> +
  0.500+0.000j |1111>}

In [896]:
# solutions_in_true_basis[0]
Qy*solutions_in_true_basis[0]

In [884]:
Qy * solutions_in_true_basis[0]aaa

AssertionError: PauliwordOps defined for different number of qubits

In [513]:
state = sym.QuantumState([[1, 0, 1, 0, 1, 1, 1, 1]])
Qy_inZ_basis * state


AssertionError: PauliwordOps defined for different number of qubits

In [ ]:
state_normal = R.dagger * state
Qy*state_normal

AssertionError: PauliwordOps defined for different number of qubits

In [ ]:
state_normal

 0.000+0.500j |0000> +
 0.500+0.000j |0011> +
-0.500+0.000j |1100> +
 0.000+0.500j |1111>

In [ ]:
odd_Qy_mask = np.array(list(zip([False]*N, [True]*N))).reshape([-1])
odd_Qy_mask

array([False,  True, False,  True, False,  True])

In [ ]:
bitstrings[]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1]])

In [ ]:
Qz = Qz_tot(N)
Qz

-0.250+0.000j IIIIIIIIIIIIIIIZ +
 0.250+0.000j IIIIIIIIIIIIIIZI +
-0.250+0.000j IIIIIIIIIIIIIZII +
 0.250+0.000j IIIIIIIIIIIIZIII +
-0.250+0.000j IIIIIIIIIIIZIIII +
 0.250+0.000j IIIIIIIIIIZIIIII +
-0.250+0.000j IIIIIIIIIZIIIIII +
 0.250+0.000j IIIIIIIIZIIIIIII +
-0.250+0.000j IIIIIIIZIIIIIIII +
 0.250+0.000j IIIIIIZIIIIIIIII +
-0.250+0.000j IIIIIZIIIIIIIIII +
 0.250+0.000j IIIIZIIIIIIIIIII +
-0.250+0.000j IIIZIIIIIIIIIIII +
 0.250+0.000j IIZIIIIIIIIIIIII +
-0.250+0.000j IZIIIIIIIIIIIIII +
 0.250+0.000j ZIIIIIIIIIIIIIII

In [36]:
list(itertools.permutations(allowed_Y_2, r=N))

[((0, 0), (0, 1)), ((0, 1), (0, 0))]

In [14]:
import itertools
allowed_Y_1 = [(1,0), (1,1)]
allowed_Y_2 = [(0, 0), (0, 1)]
product1 = list(itertools.product(allowed_Y_1, repeat=N))
#product2 = list(itertools.product(allowed_Y_2, repeat=N)) Adds 0000 and 0101 which aren't annihilated by Qy_inZ
product2 = list(itertools.permutations(allowed_Y_2, r=N))


arr1 = np.array(product1)
arr2 = np.array(product2)
arr = np.concatenate((arr1, arr2))
arr_updated = arr.reshape(arr.shape[0],-1)

arr_updated

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [19]:
import itertools
allowed_Y = [(1,0), (1,1)]
product = list(itertools.product(allowed_Y, repeat=N))

arr = np.array(product)
arr = arr.reshape(arr.shape[0],-1)

arr

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

In [20]:
arr

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1]])

In [30]:
for state in [list(i) for i in itertools.product([0, 1], repeat = 2 * N)]:
    qstate = sym.QuantumState([state])
    print(qstate, Qy_inZ_basis * qstate)

 1.000+0.000j |0000>  1.000+0.000j |0000>
 1.000+0.000j |0001> 
 1.000+0.000j |0010>  0.500+0.000j |0010>
 1.000+0.000j |0011>  0.500+0.000j |0011>
 1.000+0.000j |0100> 
 1.000+0.000j |0101> -1.000+0.000j |0101>
 1.000+0.000j |0110> -0.500+0.000j |0110>
 1.000+0.000j |0111> -0.500+0.000j |0111>
 1.000+0.000j |1000>  0.500+0.000j |1000>
 1.000+0.000j |1001> -0.500+0.000j |1001>
 1.000+0.000j |1010> 
 1.000+0.000j |1011> 
 1.000+0.000j |1100>  0.500+0.000j |1100>
 1.000+0.000j |1101> -0.500+0.000j |1101>
 1.000+0.000j |1110> 
 1.000+0.000j |1111> 


In [15]:
solutions = {}
for i in range(arr.shape[0]):
    #state =  sym.QuantumState(arr[i,:].reshape([1,-1]), [1]) 
    state =  sym.QuantumState(arr_updated[i,:].reshape([1,-1]), [1]) 
    solutions[i] = R.dagger * state
    # solutions[i] = state

solutions

{0:  0.500+0.000j |0000> +
  0.000-0.500j |0011> +
  0.000-0.500j |1100> +
 -0.500+0.000j |1111>,
 1:  0.000+0.500j |0000> +
 -0.500+0.000j |0011> +
  0.500+0.000j |1100> +
  0.000+0.500j |1111>,
 2:  0.000+0.500j |0000> +
  0.500+0.000j |0011> +
 -0.500+0.000j |1100> +
  0.000+0.500j |1111>,
 3: -0.500+0.000j |0000> +
  0.000-0.500j |0011> +
  0.000-0.500j |1100> +
  0.500+0.000j |1111>,
 4:  0.000-0.500j |0101> +
 -0.500+0.000j |0110> +
  0.500+0.000j |1001> +
  0.000-0.500j |1010>,
 5:  0.000-0.500j |0101> +
  0.500+0.000j |0110> +
 -0.500+0.000j |1001> +
  0.000-0.500j |1010>}

In [17]:
mesons, baryons

([ 1.000+0.000j |0011>,
   1.000+0.000j |0110>,
   1.000+0.000j |1001>,
   1.000+0.000j |1100>],
 [ 1.000+0.000j |0000>])

In [ ]:
solutions[1] - solutions[3]

 0.500+0.500j |0000> +
-0.500+0.500j |0011> +
 0.500+0.500j |1100> +
-0.500+0.500j |1111>

In [ ]:
solutions[0]

 0.500+0.000j |0000> +
 0.000-0.500j |0011> +
 0.000-0.500j |1100> +
-0.500+0.000j |1111>

In [ ]:
solutions[0] + solutions[1] - solutions[2] + solutions[3]

-1.000-1.000j |0011> +
 1.000-1.000j |1100>

In [ ]:
ind = 1

state =  sym.QuantumState(arr[ind].reshape([1,-1]), [1]) 
R.dagger * statea

 0.000+0.500j |0000> +
-0.500+0.000j |0011> +
 0.500+0.000j |1100> +
 0.000+0.500j |1111>

In [ ]:
state =  sym.QuantumState(arr[3].reshape([1,-1]), [1]) 
Qy_inZ_basis * state

In [ ]:
Qy * R.dagger * state

In [ ]:
R.dagger * state

-0.500+0.000j |0000> +
 0.000-0.500j |0011> +
 0.000-0.500j |1100> +
 0.500+0.000j |1111>

In [ ]:

 
letters = ['10', '11']
 
# size of combination is set to 3
a = itertools.combinations(letters, 3) 
y = [' '.join(i) for i in a]
 
print(y)

[]


In [ ]:
lst = [2, 3]
combs = []

els = [list(x) for x in itertools.combinations(lst, N)]
els

[[2, 3]]

In [ ]:
lst

[2, 3, 2, 3]

In [ ]:
lst

[2, 3, 2, 3]

[('10', '10'), ('10', '11'), ('11', '10'), ('11', '11')]

[('10', '10'), ('10', '11'), ('11', '10'), ('11', '11')]

In [ ]:
Qy * sym.QuantumState([[1, 0, 0, 1]]) - Qy * sym.QuantumState([[0, 1, 1, 0]])

In [514]:
state1 = sym.QuantumState([[0, 1, 1, 0]])
state2 = sym.QuantumState([[1, 0, 0, 1]])

In [521]:
 Qx * (state1 - state2)

In [519]:
state1.dagger * Qy * state1

0j

In [553]:
Qy

-0.250+0.000j IIIIIIXY +
 0.250+0.000j IIIIIIYX +
-0.250+0.000j IIIIXYII +
 0.250+0.000j IIIIYXII +
-0.250+0.000j IIXYIIII +
 0.250+0.000j IIYXIIII +
-0.250+0.000j XYIIIIII +
 0.250+0.000j YXIIIIII

In [583]:
op  = Qy * Qx * Qz

In [584]:
# op

In [585]:
vals, vecs = np.linalg.eigh(op.to_sparse_matrix.toarray())
epsilon = 1e-12
mask = np.abs(vals)<epsilon


In [590]:
indices = np.where(mask)[0]
indices

array([ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
       123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
       136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
       149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
       162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
       175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187,
       188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
       201, 202, 203, 204, 205, 206, 207, 208, 209, 210])

In [591]:
index = indices[0]

In [596]:
psi = sym.QuantumState.from_array(vecs[:, index].reshape([-1, 1]))
Qz * psi 

-0.001+0.002j |01001001> +
 0.000+0.002j |01001100> +
-0.033+0.016j |01011000> +
 0.006-0.005j |01011011> +
-0.018-0.014j |01011110> +
 0.003+0.002j |01100001> +
 0.025-0.007j |01100010> +
 0.058-0.007j |01100100> +
-0.011-0.076j |01100111> +
 0.226+0.060j |01101000> +
-0.005+0.022j |01101011> +
 0.019+0.032j |01101101> +
 0.038-0.001j |01101110> +
-0.250-0.047j |01110000> +
 0.019-0.028j |01110011> +
-0.023-0.001j |01110110> +
 0.049-0.013j |01111001> +
-0.029-0.096j |01111010> +
-0.064+0.018j |01111100> +
 0.018-0.042j |01111111> +
-0.045+0.018j |10000000> +
 0.007-0.005j |10000011> +
 0.001-0.002j |10000101> +
-0.000-0.002j |10000110> +
 0.000+0.002j |10001001> +
-0.003-0.002j |10010001> +
-0.009+0.004j |10010010> +
-0.026-0.009j |10010100> +
 0.005+0.081j |10010111> +
-0.112-0.036j |10011000> +
 0.002-0.011j |10011011> +
-0.001-0.019j |10011101> +
 0.014-0.039j |10011110> +
-0.016+0.002j |10100001> +
-0.114-0.024j |10100100> +
 0.003-0.011j |10100111> +
-0.052+0.040j |10101101> +
-

In [597]:
import scipy as sp

In [804]:
Qy_mat = Qy.to_sparse_matrix.toarray()
Qy_ns = sp.linalg.null_space(Qy_mat)

# np.allclose(Qy_mat@Qy_ns[:,3], np.zeros(Qy_ns.shape[0]))

Qz_mat = Qz.to_sparse_matrix.toarray()
Qz_ns = sp.linalg.null_space(Qz_mat)

Qx_mat = Qx.to_sparse_matrix.toarray()
Qx_ns = sp.linalg.null_space(Qx_mat)

In [807]:
null_vecs_Qz = {i: sym.QuantumState.from_array(op_ns[:, i].reshape([-1,1])) for i in range(Qz_ns.shape[1])}
null_vecs_Qz

{0:  0.476-0.000j |0101> +
 -0.330-0.627j |0110> +
 -0.147+0.151j |1001> +
 -0.000-0.476j |1010>,
 1:  0.326-0.000j |0101> +
 -0.030+0.405j |0110> +
 -0.297-0.731j |1001> +
  0.000-0.326j |1010>,
 2:  1.000-0.000j |1100>,
 3:  1.000-0.000j |1111>,
 4:  1.000-0.000j |0011>,
 5:  1.000-0.000j |0000>}

In [644]:
op  = Qy + Qx + Qz
op_mat = op.to_sparse_matrix.toarray()
op_ns = sp.linalg.null_space(op_mat)

null_vecs = [sym.QuantumState.from_array(op_ns[:, i].reshape([-1,1])) for i in range(op_ns.shape[1])]

In [646]:
for vec in null_vecs:
    out_y = Qy*vec
    out_x = Qx*vec
    out_z = Qz*vec
    if out_x.n_terms== 0 and out_y.n_terms==0 and out_z.n_terms == 0:
        print(vec)


 1.000-0.000j |1100>
 1.000-0.000j |1111>
 1.000-0.000j |0011>
 1.000-0.000j |0000>


In [ ]:
op  = Qy * Qx * Qz

In [651]:
psi = sym.QuantumState([[1,0,0,1],
                  [0,1,1,0]], [1,-1]).normalize
psi

 0.707+0.000j |1001> +
-0.707+0.000j |0110>

In [653]:
Qy * psi

In [654]:
Qx * psi

In [655]:
Qz * psi

In [656]:
op*psi

In [692]:
op  = Qy + Qx +Qz

vals, vecs = np.linalg.eigh(op.to_sparse_matrix.toarray())
inds = np.where(np.abs(vals)<1e-12)[0]

In [693]:
valid_states = vecs[:, inds]

In [694]:
psi = sym.QuantumState.from_array(valid_states[:,0].reshape([-1,1]))

In [696]:
Qy*psi

 0.000+0.500j |0010>